
// Location Data Tables


// Location Data - Nested by Biome and Location Type
const locationData = {
    forest: {
        mundane: {
            names: [
                "Old Logging Camp",
                "Hunter's Blind",
                "Deer Trail",
                "Creek Crossing",
                "Worn Stone Bridge",
                "Bandit Ambush Point",
                "Logging Cabin",
                "Charred Remains",
                "Overgrown Ruin",
                "Trapper's Trail",
                "Murky Pond",
                "Tangled Thicket",
                "Overlook",
                "Shadowed Gulch",
                "Wolf Den",
                "Old Mill Site",
                "Mineral Spring",
                "Fallen Log Crossing",
                "Spiderwebbed Path",
                "Twisted Oak Clearing",
                "Raven's Peak",
                "Gloomwood Path",
                "Mossy Outcrop",
                "Stone Archway",
                "Echoing Hollow",
                "Wildflower Meadow",
                "Charred Tree",
                "Lost Firepit",
                "Birdsong Dell",
                "Muddy Creek Bank",
                "Old Bones Trail",
                "Rest Stop Rock",
                "Rotting Tree",
                "Deer Run"
            ],
            descriptions: [
                "A weathered stone bridge spanning a deep ravine, showing signs of disrepair.",
                "A clearing where a band of outlaws has set up a makeshift camp.",
                "A small, rundown cabin used by hunters seeking game in the forest.",
                "A shallow creek that must be forded to continue along the path.",
                "A clearing littered with decaying logs and rusting equipment from a bygone logging operation.",
                "A sudden and unexpected depression in the forest floor, partially filled with water.",
                "A small, neglected shrine dedicated to a forgotten forest deity.",
                "A secret stash of traps and supplies hidden by a long-absent trapper.",
                "A small body of stagnant water, barely visible beneath the thick canopy."
            ],
            complications: [
                "A troll lives under the bridge, demanding a toll for passage.",
                "The bandits are led by a ruthless killer with a vendetta.",
                "A wendigo stalks the hunting cabin, preying on lone travelers.",
                "The creek is infested with leeches that transmit a debilitating disease.",
                "Animated logging equipment haunts the site, attacking anyone who enters.",
                "The sinkhole leads to an underground cave system with unknown dangers.",
                "A vengeful spirit haunts the shrine, punishing those who disturb it.",
                "The trapper's cache is guarded by a magical construct.",
                "The murky pond contains a hidden portal to another dimension.",
                "The stones whisper secrets that drive you mad"
            ]
        },
        fantastic: {
            names: [
                "The Emerald Grove",
                "Feywild Border Crossing",
                "The Whispering Cairn",
                "The Living Labyrinth",
                "The Shadow Pool",
                "The Petrified Waterfall",
                "The Treant King's Court",
                "The Moonlit Clearing",
                "The Sunken Shrine of Silvanus",
                "The Crystalline Caverns",
                "The Everbloom Glade",
                "The Gnarled Root Gate",
                "The Sprite Village",
                "The Banshee's Howl",
            ],
            descriptions: [
                "A grove of ancient trees with emerald leaves that shimmer in the sunlight.",
                "A spot where the veil between the Material Plane and the Feywild is thin.",
                "An ancient stone cairn that whispers forgotten prophecies.",
                "A constantly shifting maze of living trees and thorny vines.",
                "A pool of water that reflects not the surrounding forest, but glimpses of other worlds.",
                "A waterfall frozen in time, turned to solid crystal.",
                "A gathering of treants (ancient talking trees), centered on a massive, elder tree.",
                "A place only illuminated by moonlight where strange creatures gather.",
                "A place where you can get lost in a deep dark pool",
                "A place where a tree may come to life",
                "A cave system made of pure crystal.",
                "A forest with blooms that are permenantly in bloom",
                "Tree roots that are connected to another plane",
                "A Village of mischievous Sprites",
                "It howls that can be heard for miles"
            ],
            complications: [
                "The grove is protected by a powerful dryad.",
                "Crossing the border attracts the attention of jealous fey creatures.",
                "The whispers can drive listeners mad with knowledge of the future.",
                "Getting lost in the labyrinth means facing dangerous fey creatures.",
                "Gazing into the pool can trap your soul in another dimension.",
                "Touching the crystal can turn you to stone.",
                "Angering the treants will bring the forest down upon you.",
                "Creatures are drawn to it",
                "You may drown",
                "The trees can move and change in a blink of an eye",
                "The crystal structures block magic.",
                "The permenant blooms attract terrible predators",
                "There are terrible whispers",
                "The Sprites will steal your stuff",
                "The Howl draws in the dark forces"
            ]
        }
    },
    plains: {
        mundane: {
            names: [
                "Abandoned Farmhouse",
                "Wagon Trail",
                "Lone Oak",
                "Dry Gulch",
                "Cattle Skull",
                "Dust Devil",
                "Prairie Dog Town",
                "Caravan Wreck",
                "Windmill Ruin",
                "Abandoned Well",
                "Old Scarecrow",
                "Sunken Cart",
                "Vulture Perch",
                "Stone Cairn"
        ],
        descriptions: [
            "A deserted farmhouse with broken windows and a creaking porch.",
            "A dusty trail worn by countless wagons heading west.",
            "A solitary oak tree standing sentinel over the flatlands.",
            "A deep, dry gully carved by ancient floods.",
            "A sun-bleached skull of a long-dead bovine.",
            "A swirling vortex of dust and wind.",
            "An extensive network of burrows and mounds created by prairie dogs.",
            "Scattered wreckage and supplies from a destroyed wagon train.",
            "A dilapidated windmill, its sails long gone.",
            "A stone-lined well, long since dried up and abandoned.",
            "A ragged scarecrow standing in a field of withered crops.",
            "A broken down cart sinking into the ground",
            "A cluster of sun beaten stones",
            "An eerie spot to lay down."
        ],
        complications: [
            "The farmhouse is infested with rats carrying a dangerous plague.",
            "Bandits prey on travelers along the wagon trail.",
            "The oak tree is a frequent target for lightning strikes.",
            "The gulch hides a nest of venomous snakes.",
            "The skull is cursed, bringing bad luck to those who touch it.",
            "The dust devil is a minor elemental, attacking those who get too close.",
            "The prairie dogs are fiercely territorial and carry disease.",
            "The wreckage is haunted by the ghosts of the travelers who perished.",
            "The windmill is home to a monstrous owl.",
            "A creature is trapped down there.",
            "The field has creatures that try to pull you down",
            "A demon lives inside",
            "The vulture wants to pick your bones.",
            "The stones send out a bad energy"
        ]
    },
    fantastic: {
        names: [
            "Floating Mesa",
            "The Mirage Well",
            "Windstone Circle",
            "Grave of the Sky Kraken",
            "The Rainbow Arch",
            "Singing Stones",
            "The Plains Beasts Lair",
            "Whispering Grass",
            "Gnomish Village",
            "The Obsidian Monolith",
            "The Stargazer's Platform",
            "The Sunken Zepplin",
            "Crystal Field",
            "Giant Rock Bird Nest"
        ],
        descriptions: [
            "A mesa that floats gently above the plains, supported by ancient magic.",
            "A well that produces only illusory water and reflects impossible visions.",
            "A circle of standing stones that hum with ethereal energy.",
            "A massive skeleton embedded in the plains, said to be from a creature that once swam in the sky.",
            "A shimmering archway formed by pure light.",
            "A cluster of stones that produce melodies when touched.",
            "A sinkhole leading to the lair of a massive, land-bound kraken.",
            "Grass that whispers secrets to those who listen closely.",
            "A hidden village of gnomes built into the roots of a giant tree.",
            "A dark rock that seems to absorb light",
            "It reflects the nightsky during the day.",
            "A relic of a long lost civilization, still working.",
            "It creates new light and is warm",
            "Birds like living on it."
        ],
        complications: [
            "The mesa is slowly drifting toward a dangerous storm.",
            "The illusions can trap unwary travelers in a dream world.",
            "The stones amplify psychic abilities, but also attract malevolent entities.",
            "The skeleton is haunted by the restless spirit of the Sky Kraken.",
            "Crossing the arch teleports you to a random location on the Material Plane.",
            "The melodies can drive listeners mad with repetitive tunes.",
            "The kraken is still alive and very hungry.",
            "The secrets are often lies meant to mislead or corrupt.",
            "The gnomes are fiercely protective of their home and distrust outsiders.",
            "The light drains your sanity",
            "The stars are not there but are an illusion.",
            "It summons terrible storms.",
            "Scarab monsters lay eggs in your ears.",
            "Its home to massive rock birds"
        ]
    }
},
mountains: {
    mundane: {
        names: [
            "Goat Trail",
            "Mountaintop Shrine",
            "Cave Entrance",
            "Crumbling Watchtower",
            "Shepherd's Hut",
            "Abandoned Mine Shaft",
            "Frozen Lake",
            "Stone Quarry",
            "Avalanche Zone",
            "Hidden Pass",
            "Echoing Canyon",
            "Glacier's Edge",
            "Lost Prospector's Camp",
            "Rope Bridge"
        ],
        descriptions: [
            "A narrow path winding precariously along a cliff face.",
            "A small shrine dedicated to a mountain deity.",
            "The mouth of a dark and unexplored cave.",
            "The ruins of an old stone watchtower, battered by wind and snow.",
            "A small, sturdy hut used by shepherds tending their flocks.",
            "A dark, flooded mine shaft with broken supports",
            "A lake frozen solid all year round, with treacherous ice.",
            "A source of stone.",
            "Signs show this is a danger zone.",
            "A hidden path known to natives.",
            "Loud sounds come back to you.",
            "The point where the glacier meets the earth",
            "Signs of a life lost",
            "A scary bridge hanging on for dear life."
        ],
        complications: [
            "The trail is prone to rockslides.",
            "The shrine has been defiled by vandals.",
            "The cave is inhabited by a monstrous creature.",
            "The watchtower is about to collapse.",
            "The shepherd is a recluse with a dark secret.",
            "A monster lives there",
            "The ice is prone to crack",
            "It creates constant avalanches",
            "Anything can happen on a trail",
            "Wind and storms can hit anytime",
            "It summons all types of creatures",
            "It tests your resolve",
            "They will push you down",
            "The rope is about to break"
        ]
    },
    fantastic: {
        names: [
            "Crystal Peak",
            "The Elemental Forge",
            "The Sky Bridge",
            "The Roc's Nest",
            "The Dragon's Hoard",
            "Giant's Grave",
            "The Cloud Altar",
            "The Stone Golem Quarry",
            "Mirror Caverns",
            "The Thunderlord's Cairn",
            "Labyrinth of the Shifting Stones",
            "Aerie of the Storm Eagles",
            "The Petrified City of Aerthos",
            "The Wellspring of Wishes"
        ],
        descriptions: [
            "A mountain peak covered in enormous, shimmering crystals.",
            "A hidden forge powered by the elemental forces of the mountain.",
            "A bridge made of solidified clouds connecting two mountain peaks.",
            "A nest built by giant Rocs",
            "Guarded by a fearsome dragon.",
            "Home of a long forgotten race of giants",
            "A site of natural storms",
            "Can only find this if you want to.",
            "An optical illusion",
            "A long forgotten place.",
            "A cave system with strange creatures",
            "It is always storming near",
            "People come to remember those lost to time.",
            "A place to come to wish for great things"
        ],
        complications: [
            "The crystals emit a disorienting energy.",
            "The forge is guarded by a fire elemental.",
            "The bridge is unstable and prone to collapsing.",
            "The Rocs will protect their territory",
            "The dragon is fiercely protective and greedy.",
            "Animate skeletons",
            "You will be struck by lightning",
            "The golems test you and kill you",
            "You can get lost forever",
            "Storms of past are relived.",
            "Everything is at random",
            "Eagles can carry you off",
            "All are cursed.",
            "A demon is bound there and will trick you."
        ]
    }
},
swamp: {
    mundane: {
        names: [
            "Muddy Bank",
            "Cypress Grove",
            "Hanging Moss",
            "Old Boat",
            "Gator Nest",
            "Quicksand Pit",
            "Spanish Moss Bridge",
            "Smuggler's Shack",
            "Stagnant Pool",
            "Firefly Meadow",
            "Fungal Rot",
            "Crocodile Nesting Ground",
            "Ghost Orchid Patch",
            "Half-Sunken Rowboat"
        ],
        descriptions: [
            "The murky water is black as ink.",
            "Cypress Trees full of roots are old and gnarled",
            "Moss dangles thick like curtains, obscuring everything.",
            "A broken ship sits sinking into the swamp.",
            "Filled with gator eggs",
            "Where the ground turns to goo.",
            "Strands of it form a bridge you might be able to cross.",
            "A barely visible shack is barely there and falling apart",
            "The still water is a breeding ground.",
            "A glade where fireflies dance.",
            "Plants are growing",
            "A place where many nest",
            "Strange beautiful flowers here.",
            "Barely visable but it still floats"
        ],
        complications: [
            "Hungry gators.",
            "The trees move slowly",
            "The moss causes hallucinations",
            "It summons snakes",
            "The queen gator attacks.",
            "It will swallow you.",
            "It might break any minute.",
            "A hag lives here",
            "It summons demons",
            "Vampires are there.",
            "Undead grow near",
            "Everything gets very loud.",
            "The spores will infect you and grow",
            "The boat may summon monsters or be haunted",
            "They are protected and you get hurt more often.",
            ]
        },
    fantastic: {
        names: [
            "Lizard King's Throne",
            "Will-o-wisp Nest",
            "Floating Hut",
            "Vortex Bloom",
            "The Sunken Ziggurat",
            "Hydra's Lair",
            "The Mire of Lost Souls",
            "Circle of Standing Stones",
            "The Whispering Reeds",
            "The Grotto of Glowing Fungus",
            "Serpent's Skull Isle",
            "The Bone Orchard",
            "Altar of the Drowned God",
            "Bog Mother's Bog"
        ],
        descriptions: [
            "A seat of power claimed by an ancient lizard king",
            "Orbs of light dance as you walk closer.",
            "Hidden deep in the swamp, held afloat by magic.",
            "It is said to connect other words. - You are transported, you are healed, it will give water.",
            "Steps lead down into dark waters",
            "Full of many heads and they eat well",
            "The sounds of suffering come from here.",
            "These stones are all to big and they hum",
            "They seem to have some form of communication.",
            "It may be poisonous but it looks so nice.",
            "Teeth and bone are the stone you walk on",
            "Trees bear fruit of bones and not fruit",
            "Everything here wants you dead.",
            "A mother protects this space"
        ],
        complications: [
            "He is not friendly",
            "They are hungry.",
            "Anyone who enters never comes out.",
            "It teleports you into the earth.",
            "Undead gaurd it.",
            "Cut off one head, two more grow",
            "Souls will attack and try to consume you.",
            "The stones can drive you mad",
            "There are hidden Lizardfolk",
            "The toxins and mushrooms can kill you if you are not careful",
            "You will be eaten alive",
            "They scream and yell all the time.",
            "It has not been nice to those who have defiled it.",
            "She eats well and is terrible"
        ]
    }
},
arctic: {
        mundane: {
            names: [
                "Icy Cave",
                "Frozen Corpse",
                "Sealed Vault",
                "Sleet Storm",
                "Aurora Borealis",
                "Glacier Crevasse",
                "Abandoned Research Station",
                "Snowdrift Maze",
                "Hidden Hot Spring",
                "Whale Graveyard",
                "Migration Trail",
                "Ominous Black Ice",
                "Frozen Waterfall",
                "Ancient Cairn"
            ],
            descriptions: [
                "The icy cave is the source of fresh water",
                "You can make out his face and he looks to be in pain",
                "The door is cracked open just enough to see inside",
                "White out conditions",
                "A beautiful sky dance",
                "A deep hidden hole",
                "Lights flicker on and off for some reason",
                "Snow walls block the wind here",
                "A break in the ice shows warm waters",
                "Home to thousands of long dead whales",
                "This route goes on for miles and miles",
                "A dark patch to avoid",
                "A permenantly frozen lake",
                "It has an evil aura"
            ],
            complications: [
                "It is guarded by a worm.",
                "He comes back to life.",
                "It holds something terrible.",
                "It causes frostbite.",
                "It makes you dance until you die",
                "It leads to the center of the earth",
                "There are terrible experiments",
                "You can get lost easily",
                "All the water comes to life",
                "They curse those who walk on it",
                "Creatures with follow",
                "It will drag you down",
                "There is something lost inside",
                "Storms will come and they will make you lost",
                "The stones whisper to you"
            ]
        },
    fantastic: {
        names: [
            "Frozen Dragon",
            "Windigo Nest",
            "Ice Fortress",
            "Snow Angel Grave",
            "The Mirror Glacier",
            "City of Crystalline Spires",
            "Heart of the Frost Giant",
            "The Auroral Veil",
            "The Well of Winter's Tears",
            "Frost Lich's Ziggurat",
            "The Shambling Iceberg",
            "The Cave of Shivering Souls",
            "Ymir's Thumb",
            "Gate to the Ice Plane"
        ],
        descriptions: [
            "The scales glisten in the blue ice.",
            "This is where they are born.",
            "Only the wind howls here.",
            "A beautiful grave covered in wind blown snow",
            "The ice creates illusions",
            "It glistens and glimmers",
            "The ground here is always cold and it emits energy",
            "The light changes based on the people near",
            "The water heals any wounds",
            "He may come back to life",
            "A large iceberg walks.",
            "Home to souls",
            "A long pillar on the horizion.",
            "A doorway that takes you somewhere else"
        ],
        complications: [
            "It might come back to life.",
            "They are starving and see you as food",
            "It keeps moving and crushing things.",
            "It has a hypnotic power.",
            "It will trap you forever",
            "Creatures will take you",
            "Giants come to protect it",
            "It shows lies of what you wish.",
            "The heat is taken.",
            "A storm happens and he revives",
            "It eats ice.",
            "The souls want to latch on",
            "If it falls the world will end",
            "It drains all warmth"
        ]
    }
},
desert: {
    mundane: {
        names: [
            "Scorpion Den",
            "Hidden Oasis",
            "Sandstorm",
            "Cactus Garden",
            "Canyon Pass",
            "Dry Riverbed",
            "Old Bandit Camp",
            "Mirage Lake",
            "Dust Devil Swirl",
            "Ancient Ruins",
            "Trading Post",
            "Forgotten Well",
            "Terracotta Pillars",
            "Sun Bleached Oasis",
            "The Lonely Grave"
        ],
        descriptions: [
            "Scorpions swarm around as you get closer.",
            "A pocket of relief from the harsh desert",
            "The visibility is zero.",
            "Prickly flowers line this location",
            "Rock walls line the canyon pass",
            "Bone fragments lay here",
            "The wind howls",
            "The heat radiates everywhere",
            "You can get turned around quick",
            "It is easy to get lost",
            "Strange creatures stop here.",
            "Old ruins of a town.",
            "It's still working.",
            "These support the world",
            "You're not sure where you're going",
            "Its hard to see but you are being watched."
        ],
        complications: [
            "Their poison can knock out a horse",
            "The water is all but gone.",
            "You can easily get lost or separated.",
            "The flowers cause hallucinations",
            "The roof may come crashing down",
            "It can cause sickness",
            "The sand may claim what belongs to you",
            "The people may betray you.",
            "Sand may turn into quicksand",
            "A monster attacks from above",
            "Spirits wander",
            "There is never anything good to trade.",
            "You can drown",
            "A tornado may arise",
            "They may come back and attack",
            "There is no one here only you."
        ]
    },
    fantastic: {
        names: [
            "Obelisk of Thirst",
            "Sand Kraken Grave",
            "Crystal Scarab Mound",
            "Quicksand Whirlpool",
            "The Oasis of Whispering Palms",
            "The Djinn's Prison",
            "The Shifting Sands Bazaar",
            "The Sunken Pyramid of Akhet",
            "The Mirage Dragon's Hoard",
            "The Dune Sea Leviathan",
            "The Obsidian City of Night",
            "Bird Kin Nest",
            "Terracotta Giants",
            "Scorpion King's Tomb",
            "Living Fire"
        ],
        descriptions: [
            "It emits heat and you can feel its power",
            "The skeleton tells a horrible story",
            "They scuttle in and out of the sand.",
            "It appears out of nowhere and will swallow you",
            "Guarded by ghouls, the Oasis provides water that comes from the earth",
            "The creature does what it wants to you.",
            "It is a lie to take your soul.",
            "Long before anything existed was built.",
            "A fire dragon has fallen here.",
            "An ancient creature sleeps beneath.",
            "It comes out of nowhere and disappears.",
            "It keeps moving and changing."
        ],
        complications: [
            "It makes you incredibly thirsty and you start hallucinating",
            "It sends out a psionic message to flee.",
            "They can control the sand and the temperature.",
            "It is a portal to another world.",
            "The desert creatures will drain your mind and follow",
            "It has chains and it seems to want help to trick you",
            "All the water will make you forget.",
            "They will take your breath.",
            "Scarab monsters lay eggs in your ears.",
            "Scarab monsters lay eggs in your ears.",
            "Sand can be made out of the monsters",
            "Aarakocra steal you and fly away",
            "They will crush and kill",
            "There is no escape here."
        ]
    }
}
};
